FROM php:8.2.0RC1-apache
COPY ./sources/index.php /var/www/html/
COPY ./sources/main.css /var/www/html/
COPY ./sources/rebus.php /var/www/html/
COPY ./sources/rebus.png /var/www/html/
COPY ./sources/flag /var/www/html/
COPY ./sources/.htaccess /var/www/html
